.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nullcoin_qt test_nullcoin_qt
clean: FORCE
	$(MAKE) -C .. nullcoin_qt_clean test_nullcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_nullcoin_qt_check
nullcoin-qt nullcoin-qt.exe: FORCE
	 $(MAKE) -C .. nullcoin_qt
